# Base on offical Node.js Alpine image
FROM node:14-alpine

# Set working directory
WORKDIR /usr/app

RUN npm install --global pm2
# Copy package.json and package-lock.json before other files
# Utilise Docker cache to save re-installing dependencies if unchanged
COPY ./package*.json ./

# Install dependencies
RUN npm install
RUN npm install json-server -g --silent

# Copy all files
COPY ./ ./

ENV NODE_ENV production
# Build app
RUN npm run build

# Expose the listening port
EXPOSE 3000
EXPOSE 3004

# Run container as non-root (unprivileged) user
# The node user is provided in the Node.js Alpine base image
USER node

# Run npm start script when container starts
# CMD [ "pm2-runtime", "npm", "--", "start", "json-server", "--watch", "--port", "3004" , "--host", "0.0.0.0", "fakeJsonApi/db.json", "--middlewares", "singular.js"]
CMD ["sh","-c","pm2-runtime npm -- start && json-server --watch --port 3004 --host 0.0.0.0 fakeJsonApi/db.json --middlewares fakeJsonApi/singular.js"]